name: Feature / Task
description: New feature or improvement
title: "[TASK]: "
labels: ["task"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Requirement
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Steps
    validations:
      required: true

  - type: input
    id: priority
    attributes:
      label: Priority
    validations:
      required: true